github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image: 
  file: .gitpod.Dockerfile
tasks:
  - init: ${GITPOD_REPO_ROOT}/utils/init-script.sh

vscode:
  extensions:
    - dbaeumer.vscode-eslint
